name: healthy_food
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  async: ^2.11.0
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  mobile_scanner: ^5.2.3
  cached_network_image: ^3.4.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/badges/nutri-score/
    - assets/badges/nova-score/
    - assets/badges/eco-score/
    - assets/misc/
    - assets/


localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations

